# These are supported funding model platforms

github: [Sv443]
patreon: Sv443
open_collective: #
ko_fi: Sv443_
tidelift: #
community_bridge: #
liberapay: #
issuehunt: #
otechie: #
custom: ['paypal.me/Sv443']
